# Generated by Django 5.0.6 on 2024-12-16 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_usuario', '0003_alter_viaje_latituddestino_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Viaje',
        ),
    ]
